version: '3.8'

services:
  rag-app4:
    build: .
    network_mode: host  # Use host networking
    environment:
      - DEFAULT_LLM=ollama
      - DEFAULT_MODEL=gemma2:2b
      - CHUNK_SIZE=512
      - CHUNK_OVERLAP=50
      - OLLAMA_BASE_URL=http://localhost:11434  # Use localhost with host networking
      - ANONYMIZED_TELEMETRY=false
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store